/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedDepartmentSlugTableNameRouteImport } from './routes/_authenticated/$departmentSlug/$tableName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepartmentSlugTableNameRoute =
  AuthenticatedDepartmentSlugTableNameRouteImport.update({
    id: '/$departmentSlug/$tableName',
    path: '/$departmentSlug/$tableName',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/create': typeof AuthenticatedCreateRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/$departmentSlug/$tableName': typeof AuthenticatedDepartmentSlugTableNameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/create': typeof AuthenticatedCreateRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/': typeof AuthenticatedIndexRoute
  '/$departmentSlug/$tableName': typeof AuthenticatedDepartmentSlugTableNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$departmentSlug/$tableName': typeof AuthenticatedDepartmentSlugTableNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/create'
    | '/logs'
    | '/$departmentSlug/$tableName'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/create' | '/logs' | '/' | '/$departmentSlug/$tableName'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/create'
    | '/_authenticated/logs'
    | '/_authenticated/'
    | '/_authenticated/$departmentSlug/$tableName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$departmentSlug/$tableName': {
      id: '/_authenticated/$departmentSlug/$tableName'
      path: '/$departmentSlug/$tableName'
      fullPath: '/$departmentSlug/$tableName'
      preLoaderRoute: typeof AuthenticatedDepartmentSlugTableNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDepartmentSlugTableNameRoute: typeof AuthenticatedDepartmentSlugTableNameRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDepartmentSlugTableNameRoute:
    AuthenticatedDepartmentSlugTableNameRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
